chore: unify CI workflow naming

diff --git a/.github/workflows/ci-format.yml b/.github/workflows/ci-format.yml
--- a/.github/workflows/ci-format.yml
+++ b/.github/workflows/ci-format.yml
@@ -1,4 +1,4 @@
-name: Clang Format Check
+name: CI Format
 
 on:
     push:
@@ -8,9 +8,12 @@ on:
         branches:
             - main
 
+env:
+    DOCKER_WARNING: no
+
 jobs:
-    format-check:
-        name: Run Clang Format
+    format:
+        name: Clang Format
         runs-on: ubuntu-22.04
 
         steps:
@@ -40,10 +43,15 @@ jobs:
 
             - name: Check for Uncommitted Changes
               run: |
-                  if [[ -n $(git status --porcelain) ]]; then
-                    echo "Formatting required! Some files were modified."
-                    git diff
-                    exit 1
-                  else
+                  if git diff --quiet --exit-code; then
                     echo "All files are properly formatted."
+                    exit 0
                   fi
+                  echo "::error ::Formatting required. Run ./tools/format-code.sh locally and commit the result."
+                  echo ""
+                  echo "Summary of files that need formatting:"
+                  git status --short
+                  echo "::group::Formatted diff"
+                  git --no-pager diff
+                  echo "::endgroup::"
+                  exit 1
